//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeWatch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class County
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public County()
        {
            this.Records = new HashSet<Record>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<bool> Included { get; set; }
        public Nullable<int> PoliceDepartmentId { get; set; }

        [DisplayName("Total crimes")]
        public Nullable<int> TotalCrimes { get; set; }

        public Nullable<int> CrimeRateId { get; set; }

        [DisplayName("Crimes per 1000 residents (past 12 months)")]
        public Nullable<int> CrimesPer1000 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
        public virtual PoliceDepartment PoliceDepartment { get; set; }
        [DisplayName("Crime rate")]
        public virtual CrimeRate CrimeRate { get; set; }
    }
}
