//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crime
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Police_Department { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public string Location { get; set; }
        public string LSOA_Code { get; set; }
        public string LSOA_Name { get; set; }
        public string Outcome { get; set; }
    }
}
