//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeWatch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrimeWatchModel : DbContext
    {
        public CrimeWatchModel()
            : base("name=CrimeWatchModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Record> Records { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<PoliceDepartment> PoliceDepartments { get; set; }
        public virtual DbSet<CrimeRate> CrimeRates { get; set; }
        public virtual DbSet<CountyRank> CountyRanks { get; set; }
        public virtual DbSet<RecordRank> RecordRanks { get; set; }
    }
}
