//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crime
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Type { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Location { get; set; }
        public string LSOA_Code { get; set; }
        public string LSOA_Name { get; set; }
        public string Outcome { get; set; }
        public Nullable<int> Police_Department_Id { get; set; }
        public Nullable<int> County_Id { get; set; }
        public string Police_Department_Name { get; set; }
    
        public virtual County County { get; set; }
        public virtual Police_Departments Police_Departments { get; set; }
    }
}
