//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crimes_pm
    {
        public int Id { get; set; }
        public int County_Id { get; set; }
        public System.DateTime Month { get; set; }
        public int All_crimes { get; set; }
        public Nullable<int> Anti_social_behaviour { get; set; }
        public Nullable<int> Bicycle_theft { get; set; }
        public Nullable<int> Burglary { get; set; }
        public Nullable<int> Criminal_damage_and_arson { get; set; }
        public Nullable<int> Drugs { get; set; }
        public Nullable<int> Other_theft { get; set; }
        public Nullable<int> Possession_of_weapons { get; set; }
        public Nullable<int> Public_order { get; set; }
        public Nullable<int> Robbery { get; set; }
        public Nullable<int> Shoplifting { get; set; }
        public Nullable<int> Theft_from_the_person { get; set; }
        public Nullable<int> Vehicle_crime { get; set; }
        public Nullable<int> Violence_and_sexual_offences { get; set; }
        public Nullable<int> Other_crime { get; set; }
    
        public virtual County County { get; set; }
    }
}
