//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeWatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Burglary { get; set; }
        public Nullable<int> Drugs { get; set; }
        public Nullable<int> Robbery { get; set; }
        public Nullable<int> Shoplifting { get; set; }
        public int CountyId { get; set; }
        public int AllCrimes { get; set; }
        public Nullable<int> AntiSocialBehaviour { get; set; }
        public Nullable<int> BicycleTheft { get; set; }
        public Nullable<int> CriminalDamageAndArson { get; set; }
        public Nullable<int> OtherTheft { get; set; }
        public Nullable<int> PossessionOfWeapons { get; set; }
        public Nullable<int> PublicOrder { get; set; }
        public Nullable<int> TheftFromThePerson { get; set; }
        public Nullable<int> VehicleCrime { get; set; }
        public Nullable<int> ViolenceAndSexualOffences { get; set; }
        public Nullable<int> OtherCrime { get; set; }
        public Nullable<int> CrimeRateId { get; set; }
        public Nullable<int> CrimesPer1000 { get; set; }
    
        public virtual County County { get; set; }
        public virtual CrimeRate CrimeRate { get; set; }
    }
}
